In [7]:
# CompExplained YouTube Channel
# Author: Rambod Azimi

import numpy as np

In [19]:
# Array
arr = np.array([1, 2, 3, 4, 5])

my_list = [1, 2, 3, 4, 5]

print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
# 0-D Array
arr_0d = np.array(100)
print(arr_0d)

# 1-D Array
arr_1d = np.array([1, 2, 3])
print(arr_1d)

# 2-D Array (Matrix)
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(arr_2d)

# 3-D Array
arr_3d = ([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_3d)

# Higher Dimensional Arrays
# ...

100
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [40]:
# Array Indexing
arr = np.array([1, 2, 3, 4])
print(arr[0])

print(arr[0] + arr[2])

# 2-D Array
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(arr_2d[2, 0])

# 3-D Array
# arr[2, 4, 1]

1
4
7


In [47]:
# Slicing
# 1. [start:end]
# 2. [start:end:step]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[1:4])
print(arr[:4])
print(arr[4:])
print(arr[-3: -1])

[2 3 4]
[1 2 3 4]
[5 6 7 8]
[6 7]


In [52]:
# NumPy Data Types
# strings
# integer
# float
# boolean
# complex (2 + 3i)

arr = np.array([1.25, 2.0, 3.0, 4.0])

arr_2 = np.array(['rambod', 'azimi', 'comp', 'explained'])

print(arr.dtype)
print(arr_2.dtype)

float64
<U9


In [61]:
# Shape
# 0-D Array
arr_0d = np.array(100)
print(arr_0d.shape)

# 1-D Array
arr_1d = np.array([1, 2, 3])
print(arr_1d.shape)

# 2-D Array (Matrix)
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9],
                   [1, 5, 9]])
print(arr_2d.shape)

# 3-D Array
arr_3d = ([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
# ...

()
(3,)
(4, 3)


In [67]:
# Reshaping

# 1D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(4, 3)
print(new_arr)

# 1D to 3-D
new_arr_2 = arr.reshape(2, 3, 2)
print(new_arr_2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [84]:
arr_1 = np.array([-1, 2, -3, 4, 5])
arr_2 = np.array([2, 4, 6, 8, 0])

print(f"arr_1: {arr_1}")
print(f"arr_2: {arr_2}")

print(f"arr_1 type: {type(arr_1)}")
print(f"arr_2 type: {type(arr_2)}")

print(f"Data type of arr_1: {arr_1.dtype}")
print(f"Data type of arr_2: {arr_2.dtype}")

# Addition
arr_add = np.add(arr_1, arr_2)
print(f"arr_add: {arr_add}")

# Addition - version 2
arr_add = arr_1 + arr_2
print(f"arr_add: {arr_add}")

arr_add_abs = np.add(np.abs(arr_1), np.abs(arr_2))
print(f"arr_add_abs: {arr_add_abs}")

max = np.max(arr_1)
min = np.min(arr_1)
mean_1 = np.mean(arr_1)
mean_2 = np.mean(arr_2)
print(f"max: {max}")
print(f"min: {min}")
print(f"mean_1: {mean_1}")
print(f"mean_2: {mean_2}")

arr_app = np.append(arr_1, arr_2)
print(arr_app)

arr_1_sort = np.sort(arr_1)
print(arr_1_sort)

dot = np.dot(arr_1, arr_2)
print(dot)

sum_1 = np.sum(arr_1)
sum_2 = np.sum(arr_2)
print(f"sum_1: {sum_1}")
print(f"sum_2: {sum_2}")

arr_1: [-1  2 -3  4  5]
arr_2: [2 4 6 8 0]
arr_1 type: <class 'numpy.ndarray'>
arr_2 type: <class 'numpy.ndarray'>
Data type of arr_1: int64
Data type of arr_2: int64
arr_add: [ 1  6  3 12  5]
arr_add: [ 1  6  3 12  5]
arr_add_abs: [ 3  6  9 12  5]
max: 5
min: -3
mean_1: 1.4
mean_2: 4.0
[-1  2 -3  4  5  2  4  6  8  0]
[-3 -1  2  4  5]
20
sum_1: 7
sum_2: 20
